# Generated by Django 5.2.5 on 2025-08-13 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('features', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='plagiarism_check.batchupload')),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('is_plagiarized', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='plagiarism_check.batchupload')),
                ('project1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_results1', to='plagiarism_check.projectsubmission')),
                ('project2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_results2', to='plagiarism_check.projectsubmission')),
            ],
            options={
                'unique_together': {('batch', 'project1', 'project2')},
            },
        ),
    ]
