# Generated by Django 5.2.5 on 2025-08-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plagiarismresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batchupload',
            name='nested_zip_structure',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='batchupload',
            name='total_nested_zips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plagiarismresult',
            name='comparison_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='extraction_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='original_zip_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='parent_zip_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plagiarismresult',
            name='is_plagiarized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plagiarismresult',
            name='project1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_project1', to='plagiarism_check.projectsubmission'),
        ),
        migrations.AlterField(
            model_name='plagiarismresult',
            name='project2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_project2', to='plagiarism_check.projectsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='plagiarismresult',
            unique_together={('project1', 'project2')},
        ),
    ]
